name: CI Pipeline for API

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        cd api
        npm ci

    - name: Run lint
      run: |
        cd api
        npm run lint

    - name: Run tests
      run: |
        cd api
        npm test
